# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:5000/wps?service=WPS&request=DescribeProcess&version=1.0.0&identifier=DockerRun
Accepts: application/xml

###

POST http://localhost:5000/wps
Content-Type: application/xml

< ./resources/executeDeploy.xml
###

GET http://localhost:5000/wps?service=WPS&request=DescribeProcess&version=1.0.0&identifier=newprocess
Accepts: application/xml

###

GET http://localhost:5000

###

GET http://localhost:5000/deploy

###
